/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all tourism places */
    get: operations["getAllTourismPlaces"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tourism place by ID */
    get: operations["getTourismPlaceById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}/book": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new booking */
    post: operations["createTourismBooking"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bookings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get bookings for authenticated user */
    get: operations["getTourismBookingsForUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get available tourism categories */
    get: operations["getTourismCategoriesList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/locations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get available tourism locations */
    get: operations["getTourismLocationsList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tourism place statistics */
    get: operations["getTourismStatsOverview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    TourismPlace: {
      id?: string;
      title?: string;
      description?: string;
      location?: string;
      /** @description Geographic coordinates for map */
      coordinates?: {
        /** @description Latitude of the place */
        latitude: number;
        /** @description Longitude of the place */
        longitude: number;
      };
      category?: string;
      rating?: number;
      price?: number;
      /** @description Full address of the place */
      address?: string;
      /** @description Number of reviews */
      reviewsCount?: number;
      /** @description Whether the place is currently open */
      isOpen?: boolean;
      /** @description Opening hours */
      hours?: {
        /** @description Opening time (e.g. 8:00 AM) */
        open: string;
        /** @description Closing time (e.g. 5:00 PM) */
        close: string;
      };
      /** @description List of features/tags (e.g. Guided Tours, Photography) */
      features?: string[];
      /** @description Image URL (may be empty) */
      image?: string;
      /** @description Phone number for the place (optional) */
      phoneNumber?: string;
    };
    GetTourismPlacesResponse: {
      items?: components["schemas"]["TourismPlace"][];
      total?: number;
      page?: number;
      limit?: number;
      filters?: {
        location?: string | null;
        category?: string | null;
        sortBy?: string;
      };
    };
    TourismBooking: {
      bookingId: string;
      siteId: string;
      /** Format: date */
      date: string;
      /** @description Number of guests */
      guests: number;
      /**
       * Format: time
       * @description Time of booking (optional)
       */
      time?: string;
      /** @description Special requests (optional) */
      specialRequests?: string;
    };
    CreateBookingRequest: {
      /**
       * Format: date
       * @description Date of the adventure (e.g. 2024-12-31)
       */
      date: string;
      /**
       * Format: time
       * @description Time of the adventure (e.g. 02:00 PM)
       */
      time: string;
      /** @description Number of guests/participants */
      guests: number;
      /** @description Special requests (optional) */
      specialRequests?: string;
    };
  };
}
export type $defs = Record<string, never>;
export interface operations {
  createTourismBooking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBookingRequest"];
      };
    };
    responses: {
      /** @description Booking created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TourismBooking"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAllTourismPlaces: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        filter?: string;
        /** @description Search term for tourism places */
        query?: string;
        /** @description Filter by category */
        category?: string;
        /** @description Filter by location */
        location?: string;
        /** @description Field to sort by (e.g., name, rating) */
        sortBy?: string;
        /** @description Sort order (asc or desc) */
        order?: "asc" | "desc";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of tourism places */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetTourismPlacesResponse"];
        };
      };
    };
  };
  getTourismBookingsForUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of user bookings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TourismBooking"][];
        };
      };
    };
  };
  getTourismCategoriesList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of categories */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            category: string;
          }[];
        };
      };
    };
  };
  getTourismLocationsList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of locations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            location: string;
          }[];
        };
      };
    };
  };
  getTourismPlaceById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example  */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tourism place details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TourismPlace"];
        };
      };
      /** @description Place not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getTourismStatsOverview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Place statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            totalPlaces: number;
            totalCategories: number;
          };
        };
      };
    };
  };
}
