/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a list of local guides
     * @description Returns a paginated list of expert local guides with their details, credentials, languages, specializations, and tours.
     */
    get: operations["listGuides"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a specific guide by ID
     * @description Returns detailed information about a specific local guide, including credentials, languages, specializations, and tours.
     */
    get: operations["getGuideById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}/book": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Book a private guide
     * @description Book a private guide for a specific date, time, and number of people.
     */
    post: operations["bookGuide"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    Guide: {
      /** @example guide_1 */
      id?: string;
      /** @example Dr. Khaled Mostafa */
      name?: string;
      /**
       * @description Whether the guide is featured
       * @example true
       */
      featured?: boolean;
      /**
       * Format: float
       * @example 4.9
       */
      rating?: number;
      /** @example 542 */
      reviews?: number;
      /** @example 1240 */
      toursCount?: number;
      /** @example 1000 */
      pricePerDay?: number;
      /** @example 150 */
      pricePerHour?: number;
      /**
       * @example [
       *       "Licensed Egyptologist",
       *       "PhD",
       *       "UNESCO Certified",
       *       "First Aid Certified"
       *     ]
       */
      credentials?: string[];
      /**
       * @example [
       *       "English",
       *       "Arabic",
       *       "French",
       *       "German"
       *     ]
       */
      languages?: string[];
      /**
       * @example [
       *       "Egyptology",
       *       "Ancient History",
       *       "Museums"
       *     ]
       */
      specializations?: string[];
      /** @example Licensed Egyptologist with PhD in Ancient Egyptian History. Specialized in hieroglyphics and pharaonic dynasties. Published author and consultant for major museums. */
      about?: string;
      tours?: components["schemas"]["Tour"][];
    };
    Tour: {
      /** @example Pyramids of Giza Full Day Tour */
      name?: string;
      /** @example A full day tour of the Pyramids of Giza. */
      description?: string;
      /** @example 8 */
      durationHours?: number;
      /** @example 8 */
      maxPeople?: number;
      /** @example 1200 */
      price?: number;
    };
    CreateGuideBookingRequest: {
      /**
       * Format: date
       * @description Booking date (YYYY-MM-DD)
       * @example 2026-01-31
       */
      date: string;
      /**
       * Format: time
       * @description Preferred start time (24h format, e.g. 09:00)
       * @example 09:00
       */
      startTime: string;
      /**
       * @description Number of hours (full day = 8)
       * @example 8
       */
      hours: number;
      /**
       * @description Number of people
       * @example 2
       */
      people: number;
      /**
       * @description Full name of the contact person
       * @example Ahmed Youssef
       */
      fullName: string;
      /**
       * Format: email
       * @description Contact email
       * @example ahmed@example.com
       */
      email: string;
      /**
       * @description Contact phone number
       * @example +201234567890
       */
      phone: string;
    };
    GuideBooking: {
      /**
       * @description Unique booking reference
       * @example GUIDE-96608874
       */
      bookingReference: string;
      guide: components["schemas"]["Guide"];
      /**
       * Format: date
       * @description Booking date (YYYY-MM-DD)
       * @example 2026-01-31
       */
      date: string;
      /**
       * @description Number of people
       * @example 2
       */
      people: number;
      /**
       * @description Total amount paid in EGP
       * @example 300
       */
      totalPaid: number;
      paymentSummary?: {
        /**
         * @description Amount paid for guide service
         * @example 300
         */
        guideService?: number;
        /**
         * @description Total paid
         * @example 300
         */
        total?: number;
      };
    };
  };
}
export type $defs = Record<string, never>;
export interface operations {
  bookGuide: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGuideBookingRequest"];
      };
    };
    responses: {
      /** @description Guide booking confirmed */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GuideBooking"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Guide not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Guide not available for selected date/time */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getGuideById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The unique identifier of the guide
         * @example
         */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Guide details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Guide"];
        };
      };
      /** @description Guide not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listGuides: {
    parameters: {
      query?: {
        /** @description Page number (default 1) */
        page?: number;
        /** @description Number of guides per page (default 20) */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of guides */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            guides?: components["schemas"]["Guide"][];
            /** @example 1 */
            page?: number;
            /** @example 20 */
            limit?: number;
            /** @example 100 */
            total?: number;
            /** @example 5 */
            totalPages?: number;
          };
        };
      };
      /** @description Server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
