/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    SendEmailRequest: {
      /** Format: email */
      email: string;
      userName: string;
      bookingId: string;
      placeTitle: string;
      /** Format: date */
      date: string;
      guests: number;
      totalPrice: number;
    };
    SendEmailResponse: {
      success: boolean;
      message: string;
    };
    CreateBookingRequest: {
      /**
       * Format: date
       * @description Date of the adventure (e.g. 2024-12-31)
       */
      date: string;
      /**
       * Format: time
       * @description Time of the adventure (e.g. 02:00 PM)
       */
      time: string;
      /** @description Number of guests/participants */
      guests: number;
      /** @description Special requests (optional) */
      specialRequests?: string;
    };
  };
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
