ActionCodeSettings:
  type: object
  required:
    - url
  properties:
    url:
      type: string
    handleCodeInApp:
      type: boolean
    iOS:
      type: object
      properties:
        bundleId:
          type: string
    android:
      type: object
      properties:
        packageName:
          type: string
        installApp:
          type: boolean
        minimumVersion:
          type: string
    dynamicLinkDomain:
      type: string