/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/adventures": {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all adventures */
        get: operations["listAdventures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adventures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get adventure by ID */
        get: operations["getAdventureById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adventures/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book an adventure */
        post: operations["bookAdventure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adventures/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's adventure bookings */
        get: operations["getUserAdventureBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify user ID token */
        post: operations["verifyUserIdToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated user profile */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tourism": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tourism places */
        get: operations["getAllTourismPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tourism/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bookings for authenticated user */
        get: operations["getTourismBookingsForUser"];
        put?: never;
        /** Create a new booking */
        post: operations["createTourismBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tourism/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tourism place statistics */
        get: operations["getTourismStatsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tourism/locations/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available tourism locations */
        get: operations["getTourismLocationsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tourism/categories/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available tourism categories */
        get: operations["getTourismCategoriesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tourism/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tourism place by ID */
        get: operations["getTourismPlaceById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tour-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tour packages */
        get: operations["getAllTourPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tour-packages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tour package details */
        get: operations["getTourPackageById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tour-packages/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book a tour package */
        post: operations["bookTourPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kemet-mart/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get products */
        get: operations["getKemetMartProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of local guides
         * @description Returns a paginated list of expert local guides with their details, credentials, languages, specializations, and tours.
         */
        get: operations["listGuides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific guide by ID
         * @description Returns detailed information about a specific local guide, including credentials, languages, specializations, and tours.
         */
        get: operations["getGuideById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guides/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book a private guide
         * @description Book a private guide for a specific date, time, and number of people.
         */
        post: operations["bookGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kemet-mart/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cart */
        get: operations["getKemetMartCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kemet-mart/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout */
        post: operations["kemetMartCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/custom-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create custom token for user */
        post: operations["createCustomToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/users/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/users/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by UID */
        get: operations["getUserByUid"];
        put?: never;
        post?: never;
        /** Delete user by UID */
        delete: operations["deleteUserByUid"];
        options?: never;
        head?: never;
        /** Update user by UID */
        patch: operations["updateUserByUid"];
        trace?: never;
    };
    "/firebase-admin/users/by-email/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by email */
        get: operations["getUserByEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/users/{uid}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set custom claims for user */
        post: operations["setCustomClaimsForUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/users/{uid}/revoke-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh tokens for user */
        post: operations["revokeUserTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/email-verification-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate email verification link */
        post: operations["generateEmailVerificationLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase-admin/password-reset-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate password reset link */
        post: operations["generatePasswordResetLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get business analytics metrics
         * @description Returns aggregated business metrics and reports from the PostgreSQL data source.
         */
        get: operations["getAnalyticsMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger an analytics event
         * @description Records a client event for analytics processing.
         */
        post: operations["postAnalyticsEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdventureListItem: {
            id: string;
            name: string;
            description: string;
            location: string;
            rating: number;
            price: number;
            /** @description Duration (e.g. "6 hours") */
            duration: string;
            maxGroupSize: number;
            /** @description Difficulty level (e.g. "Moderate") */
            difficulty: string;
            tags: string[];
            /**
             * Format: uri
             * @description Image or icon URL
             */
            image: string;
        };
        CreateAdventureBookingRequest: {
            adventureId: string;
            /**
             * Format: date
             * @description Date of the adventure (e.g. 2024-12-31)
             */
            date: string;
            /**
             * Format: time
             * @description Time of the adventure (e.g. 02:00 PM)
             */
            time: string;
            /** @description Number of guests/participants */
            guests: number;
            /** @description Special requests (optional) */
            specialRequests?: string;
        };
        AdventureBooking: {
            bookingId: string;
            /** @description Name of the adventure activity */
            activityName: string;
            category: string;
            /**
             * Format: date
             * @description Date of the activity (e.g. 2024-12-31)
             */
            date: string;
            /**
             * Format: time
             * @description Time of the activity (e.g. 02:00 PM)
             */
            time: string;
            /** @description Number of participants */
            participants: number;
            /** @description Total price for the booking */
            total: number;
            /** @description Average rating for the adventure */
            rating: number;
            /** @description Number of reviews for the adventure */
            reviewsCount: number;
            /**
             * Format: date-time
             * @description ISO 8601 creation timestamp
             */
            createdAt: string;
        };
        AdventureBookingListItem: {
            bookingId: string;
            adventureId: string;
        };
        VerifyUserIdTokenRequest: {
            fullName: string;
            passportNumber: string;
            nationality: string;
            /** Format: date */
            dateOfBirth: string;
            /** @enum {string} */
            gender: "M" | "F";
            /** Format: date */
            expiryDate: string;
        };
        VerifyUserIdTokenResponse: {
            userId: string;
            /** Format: email */
            email: string;
        };
        LogoutUserResponse: {
            status: string;
        };
        ProfileDetailsDto: {
            firstName: string;
            lastName: string;
            bio?: string;
            phoneNumber?: string;
            countryName?: string;
            /** Format: email */
            email: string;
            /** Format: date */
            dob?: string;
            bookingsCount: number;
            favouritesCount: number;
        };
        TourismPlace: {
            id?: string;
            title?: string;
            description?: string;
            location?: string;
            category?: string;
            rating?: number;
            price?: number;
            /** @description Full address of the place */
            address?: string;
            /** @description Number of reviews */
            reviewsCount?: number;
            /** @description Whether the place is currently open */
            isOpen?: boolean;
            /** @description Opening hours */
            hours?: {
                /** @description Opening time (e.g. 8:00 AM) */
                open: string;
                /** @description Closing time (e.g. 5:00 PM) */
                close: string;
            };
            /** @description List of features/tags (e.g. Guided Tours, Photography) */
            features?: string[];
            /** @description Image URL (may be empty) */
            image?: string;
        };
        GetTourismPlacesResponse: {
            items?: components["schemas"]["TourismPlace"][];
            total?: number;
            page?: number;
            limit?: number;
            filters?: {
                location?: string | null;
                category?: string | null;
                sortBy?: string;
            };
        };
        TourismBooking: {
            bookingId: string;
            siteId: string;
            /** Format: date */
            date: string;
            /** @description Number of guests */
            guests: number;
            /**
             * Format: time
             * @description Time of booking (optional)
             */
            time?: string;
            /** @description Special requests (optional) */
            specialRequests?: string;
        };
        CreateTourismBookingRequest: {
            siteId: string;
            /** Format: date */
            date: string;
            /** @description Number of guests */
            guests: number;
            /** Format: time */
            time: string;
            /** @description Special requests (optional) */
            specialRequests?: string;
        };
        TourPackageSummary: {
            id: string;
            name: string;
            image: string;
            pricePerPerson: number;
            /** @description Discount percentage (optional) */
            discount?: number;
            rating: number;
            location: string;
        };
        TourPackageDetail: {
            id: string;
            name: string;
            image: string;
            pricePerPerson: number;
            /** @description Discount percentage (optional) */
            discount?: number;
            rating: number;
            location: string;
            availableLanguages: string[];
            included: string[];
            itinerary: string[];
            duration: string;
            groupSize: {
                min: number;
                max: number;
            };
        };
        CreateTourPackageBookingRequest: {
            tourId: string;
            /** Format: date */
            tourDate: string;
            numberOfPeople: number;
            fullName: string;
            /** Format: email */
            email: string;
            phoneNumber: string;
            /** @description Hotel name for pickup (optional) */
            hotelName?: string;
            /** @description Special requests (optional) */
            specialRequests?: string;
        };
        CreateTourPackageBookingResponse: {
            bookingId: string;
            /** @enum {string} */
            status: "confirmed" | "pending";
            message: string;
        };
        Product: {
            id?: number;
            name?: string;
            category?: string;
            price?: number;
            currency?: string;
            rating?: number;
            image?: string;
            isBestseller?: boolean;
            isPremium?: boolean;
            discountPercent?: number;
            oldPrice?: number;
        };
        GetProductsResponse: {
            data: components["schemas"]["Product"][];
            pagination: {
                page: number;
                limit: number;
                total: number;
            };
        };
        Tour: {
            /** @example Pyramids of Giza Full Day Tour */
            name?: string;
            /** @example A full day tour of the Pyramids of Giza. */
            description?: string;
            /** @example 8 */
            durationHours?: number;
            /** @example 8 */
            maxPeople?: number;
            /** @example 1200 */
            price?: number;
        };
        Guide: {
            /** @example guide_1 */
            id?: string;
            /** @example Dr. Khaled Mostafa */
            name?: string;
            /**
             * @description Whether the guide is featured
             * @example true
             */
            featured?: boolean;
            /**
             * Format: float
             * @example 4.9
             */
            rating?: number;
            /** @example 542 */
            reviews?: number;
            /** @example 1240 */
            toursCount?: number;
            /** @example 1000 */
            pricePerDay?: number;
            /** @example 150 */
            pricePerHour?: number;
            /**
             * @example [
             *       "Licensed Egyptologist",
             *       "PhD",
             *       "UNESCO Certified",
             *       "First Aid Certified"
             *     ]
             */
            credentials?: string[];
            /**
             * @example [
             *       "English",
             *       "Arabic",
             *       "French",
             *       "German"
             *     ]
             */
            languages?: string[];
            /**
             * @example [
             *       "Egyptology",
             *       "Ancient History",
             *       "Museums"
             *     ]
             */
            specializations?: string[];
            /** @example Licensed Egyptologist with PhD in Ancient Egyptian History. Specialized in hieroglyphics and pharaonic dynasties. Published author and consultant for major museums. */
            about?: string;
            tours?: components["schemas"]["Tour"][];
        };
        CreateGuideBookingRequest: {
            /**
             * @description The ID of the guide to book
             * @example guide_1
             */
            guideId: string;
            /**
             * Format: date
             * @description Booking date (YYYY-MM-DD)
             * @example 2026-01-31
             */
            date: string;
            /**
             * Format: time
             * @description Preferred start time (24h format, e.g. 09:00)
             * @example 09:00
             */
            startTime: string;
            /**
             * @description Number of hours (full day = 8)
             * @example 8
             */
            hours: number;
            /**
             * @description Number of people
             * @example 2
             */
            people: number;
            /**
             * @description Full name of the contact person
             * @example Ahmed Youssef
             */
            fullName: string;
            /**
             * Format: email
             * @description Contact email
             * @example ahmed@example.com
             */
            email: string;
            /**
             * @description Contact phone number
             * @example +201234567890
             */
            phone: string;
        };
        GuideBooking: {
            /**
             * @description Unique booking reference
             * @example GUIDE-96608874
             */
            bookingReference: string;
            guide: components["schemas"]["Guide"];
            /**
             * Format: date
             * @description Booking date (YYYY-MM-DD)
             * @example 2026-01-31
             */
            date: string;
            /**
             * @description Number of people
             * @example 2
             */
            people: number;
            /**
             * @description Total amount paid in EGP
             * @example 300
             */
            totalPaid: number;
            paymentSummary?: {
                /**
                 * @description Amount paid for guide service
                 * @example 300
                 */
                guideService?: number;
                /**
                 * @description Total paid
                 * @example 300
                 */
                total?: number;
            };
        };
        CartItem: {
            productId?: string;
        };
        GetCartResponse: {
            items?: components["schemas"]["CartItem"][];
            total?: number;
        };
        CheckoutResponse: {
            orderId?: string;
            total?: number;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            password?: string;
            displayName?: string;
            emailVerified?: boolean;
        };
        CreateUserResponse: {
            uid: string;
            email?: string;
            displayName?: string;
            emailVerified?: boolean;
        };
        User: {
            uid?: string;
            /** Format: email */
            email?: string;
            emailVerified?: boolean;
            displayName?: string;
            /** Format: uri */
            photoURL?: string;
            disabled?: boolean;
            metadata?: {
                /** Format: date-time */
                creationTime?: string;
                /** Format: date-time */
                lastSignInTime?: string;
            };
        };
        CreateHotelBookingRequest: {
            hotelId: string;
            roomId: string;
            /** Format: date */
            checkIn: string;
            /** Format: date */
            checkOut: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            guestPhone: string;
            guests: number;
            specialRequests?: string;
        };
        CreateHotelBookingResponse: {
            id?: string;
            hotelId?: string;
            roomId?: string;
            checkIn?: string;
            checkOut?: string;
            guestName?: string;
            guestEmail?: string;
            guestPhone?: string;
            guests?: number;
            /** @enum {string} */
            status?: "pending" | "confirmed" | "cancelled" | "completed";
            createdAt?: string;
            updatedAt?: string;
            pricePerNight?: number;
            nights?: number;
            subtotal?: number;
            serviceFee?: number;
            discountPercent?: number;
            discountAmount?: number;
            totalPrice?: number;
            qrCode?: string;
            /** @enum {string} */
            paymentStatus?: "pending" | "paid" | "failed" | "refunded";
            /** @enum {string} */
            paymentMethod?: "card" | "cash" | "wallet" | "bank_transfer";
            paymentTransactionId?: string;
            paymentAmount?: number;
            paymentCurrency?: string;
            paymentDate?: string;
        };
        CreateExchangeBookingRequest: {
            fromCurrency: string;
            toCurrency: string;
            amountSent: number;
            amountReceived: number;
            exchangeRate: number;
            locationId: string;
            /** Format: date */
            appointmentDate: string;
            /** Format: time */
            appointmentTime: string;
            name: string;
            phone: string;
            /** Format: email */
            email: string;
        };
        ExchangeLocation: {
            id?: string;
            name?: string;
            address?: string;
            distanceKm?: number;
            rating?: number;
            openHours?: string;
            features?: string[];
        };
        CreateExchangeBookingResponse: {
            bookingReference?: string;
            /** @enum {string} */
            status?: "confirmed" | "pending";
            reminderSent?: boolean;
            appointmentDate?: string;
            appointmentTime?: string;
            location?: components["schemas"]["ExchangeLocation"];
            exchangeDetails?: {
                fromCurrency?: string;
                toCurrency?: string;
                amountSent?: number;
                amountReceived?: number;
                exchangeRate?: number;
            };
        };
        SendEmailRequest: {
            /** Format: email */
            email: string;
            userName: string;
            bookingId: string;
            placeTitle: string;
            /** Format: date */
            date: string;
            guests: number;
            totalPrice: number;
        };
        SendEmailResponse: {
            success: boolean;
            message: string;
        };
        FirestoreSetRequest: {
            data: {
                [key: string]: unknown;
            };
        };
        FirestoreSetResponse: {
            id: string;
        };
        FirestoreQueryRequest: {
            query: {
                [key: string]: unknown;
            };
        };
        FirestoreQueryResult: {
            id: string;
            data: {
                [key: string]: unknown;
            };
        };
        FirestoreDocument: {
            id: string;
            data: {
                [key: string]: unknown;
            };
        };
        ActionCodeSettings: {
            url: string;
            handleCodeInApp?: boolean;
            iOS?: {
                bundleId?: string;
            };
            android?: {
                packageName?: string;
                installApp?: boolean;
                minimumVersion?: string;
            };
            dynamicLinkDomain?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAdventures: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of adventures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdventureListItem"][];
                };
            };
        };
    };
    getAdventureById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Adventure details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdventureListItem"];
                };
            };
            /** @description Adventure not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bookAdventure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdventureBookingRequest"];
            };
        };
        responses: {
            /** @description Booking created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdventureBooking"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserAdventureBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdventureBookingListItem"][];
                };
            };
        };
    };
    verifyUserIdToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyUserIdTokenRequest"];
            };
        };
        responses: {
            /** @description User verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyUserIdTokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutUserResponse"];
                };
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetailsDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllTourismPlaces: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                filter?: string;
                /** @description Search term for tourism places */
                query?: string;
                /** @description Filter by category */
                category?: string;
                /** @description Filter by location */
                location?: string;
                /** @description Field to sort by (e.g., name, rating) */
                sortBy?: string;
                /** @description Sort order (asc or desc) */
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tourism places */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTourismPlacesResponse"];
                };
            };
        };
    };
    getTourismBookingsForUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourismBooking"][];
                };
            };
        };
    };
    createTourismBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTourismBookingRequest"];
            };
        };
        responses: {
            /** @description Booking created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourismBooking"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTourismStatsOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Place statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalPlaces: number;
                        totalCategories: number;
                    };
                };
            };
        };
    };
    getTourismLocationsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        location: string;
                    }[];
                };
            };
        };
    };
    getTourismCategoriesList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category: string;
                    }[];
                };
            };
        };
    };
    getTourismPlaceById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tourism place details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourismPlace"];
                };
            };
            /** @description Place not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllTourPackages: {
        parameters: {
            query?: {
                category?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tour packages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourPackageSummary"][];
                };
            };
        };
    };
    getTourPackageById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tour package details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourPackageDetail"];
                };
            };
            /** @description Tour package not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bookTourPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTourPackageBookingRequest"];
            };
        };
        responses: {
            /** @description Tour package booking created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTourPackageBookingResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tour package not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getKemetMartProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProductsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGuides: {
        parameters: {
            query?: {
                /** @description Page number (default 1) */
                page?: number;
                /** @description Number of guides per page (default 20) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of guides */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        guides?: components["schemas"]["Guide"][];
                        /** @example 1 */
                        page?: number;
                        /** @example 20 */
                        limit?: number;
                        /** @example 100 */
                        total?: number;
                        /** @example 5 */
                        totalPages?: number;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGuideById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the guide */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guide details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guide"];
                };
            };
            /** @description Guide not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bookGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuideBookingRequest"];
            };
        };
        responses: {
            /** @description Guide booking confirmed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideBooking"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Guide not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Guide not available for selected date/time */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getKemetMartCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCartResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    kemetMartCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCustomToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    uid: string;
                };
            };
        };
        responses: {
            /** @description Custom token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    getUserByUid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uid: string;
                        email: string;
                    };
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteUserByUid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUserByUid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uid: string;
                    };
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uid: string;
                        email: string;
                    };
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setCustomClaimsForUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    claims: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description Claims set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    revokeUserTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    generateEmailVerificationLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description Verification link generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        link: string;
                    };
                };
            };
        };
    };
    generatePasswordResetLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description Password reset link generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        link: string;
                    };
                };
            };
        };
    };
    getAnalyticsMetrics: {
        parameters: {
            query?: {
                /** @description Start date for the analytics period (inclusive). */
                startDate?: string;
                /** @description End date for the analytics period (inclusive). */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analytics metrics successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        metrics: {
                            /** @description Name of the metric */
                            name?: string;
                            /** @description Value of the metric */
                            value?: number;
                        }[];
                        /**
                         * Format: date-time
                         * @description Time the report was generated
                         */
                        generatedAt: string;
                    };
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error code */
                        code: number;
                        /** @description Error message */
                        message: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error code */
                        code: number;
                        /** @description Error message */
                        message: string;
                    };
                };
            };
        };
    };
    postAnalyticsEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Name of the event */
                    event_name: string;
                    /** @description User identifier (optional if anonymous) */
                    user_id?: string;
                    /** @description Anonymous identifier */
                    anonymous_id?: string;
                    /**
                     * Format: date-time
                     * @description Client event time (server may override)
                     */
                    timestamp?: string;
                    context?: {
                        /** @description ios | android | web */
                        platform?: string;
                        app_version?: string;
                        os_version?: string;
                        device_model?: string;
                    };
                    properties?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Event accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: number;
                        message: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: number;
                        message: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: number;
                        message: string;
                    };
                };
            };
        };
    };
}
