/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all tour packages */
    get: operations["getAllTourPackages"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tour package details */
    get: operations["getTourPackageById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}/book": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Book a tour package */
    post: operations["bookTourPackage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    TourPackageSummary: {
      id: string;
      name: string;
      image: string;
      pricePerPerson: number;
      /** @description Discount percentage (optional) */
      discount?: number;
      rating: number;
      location: string;
    };
    TourPackageDetails: {
      id: string;
      name: string;
      image: string;
      pricePerPerson: number;
      /** @description Discount percentage (optional) */
      discount?: number;
      rating: number;
      location: string;
      availableLanguages: string[];
      included: string[];
      itinerary: string[];
      duration: string;
      groupSize: {
        min: number;
        max: number;
      };
    };
    CreateTourPackageBookingRequest: {
      /** Format: date */
      tourDate: string;
      numberOfPeople: number;
      fullName: string;
      /** Format: email */
      email: string;
      phoneNumber: string;
      /** @description Hotel name for pickup (optional) */
      hotelName?: string;
      /** @description Special requests (optional) */
      specialRequests?: string;
    };
    CreateTourPackageBookingResponse: {
      bookingId: string;
      /** @description Reference code for the booking (for display/QR) */
      bookingReference: string;
      /** @enum {string} */
      status: "confirmed" | "pending";
      message: string;
      tourId: string;
      tourName: string;
      /** Format: date */
      tourDate: string;
      /** @description Pickup time for the tour */
      pickupTime: string;
      /** @description Duration of the tour in hours */
      durationHours: number;
      /** @description Difficulty level of the tour */
      difficulty: string;
      city: string;
      included: string[];
      numberOfPeople: number;
      guestName: string;
      /** Format: email */
      guestEmail: string;
      guestPhone: string;
      totalAmount: number;
      discount: number;
      currentPrice: number;
      /** @description Discount percentage applied */
      discountPercentage: number;
    };
  };
}
export type $defs = Record<string, never>;
export interface operations {
  bookTourPackage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTourPackageBookingRequest"];
      };
    };
    responses: {
      /** @description Tour package booking created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateTourPackageBookingResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tour package not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAllTourPackages: {
    parameters: {
      query?: {
        category?: string;
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of tour packages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TourPackageSummary"][];
        };
      };
    };
  };
  getTourPackageById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example  */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tour package details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TourPackageDetails"];
        };
      };
      /** @description Tour package not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
