/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all adventures */
    get: operations["listAdventures"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get adventure by ID */
    get: operations["getAdventureById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{id}/book": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Book an adventure */
    post: operations["bookAdventure"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bookings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user's adventure bookings */
    get: operations["getUserAdventureBookings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    AdventureBookingListItem: {
      bookingId: string;
      adventureId: string;
    };
    AdventureListItem: {
      id: string;
      name: string;
      description: string;
      location: string;
      rating: number;
      price: number;
      /** @description Duration (e.g. "6 hours") */
      duration: string;
      maxGroupSize: number;
      /** @description Difficulty level (e.g. "Moderate") */
      difficulty: string;
      tags: string[];
      /**
       * Format: uri
       * @description Image or icon URL
       */
      image: string;
    };
    AdventureDetails: {
      id: string;
      name: string;
      description: string;
      location: string;
      rating: number;
      price: number;
      /** @description Duration (e.g. "6 hours") */
      duration: string;
      maxGroupSize: number;
      difficulty: string;
      tags: string[];
      /** Format: uri */
      image: string;
      /** @description Items/services included in the adventure */
      included: string[];
      /** @description Languages available for the adventure */
      availableLanguages: string[];
      /** @description Key highlights of the adventure */
      highlights: string[];
    };
    AdventureBooking: {
      bookingId: string;
      /** @description Name of the adventure activity */
      activityName: string;
      category: string;
      /**
       * Format: date
       * @description Date of the activity (e.g. 2024-12-31)
       */
      date: string;
      /**
       * Format: time
       * @description Time of the activity (e.g. 02:00 PM)
       */
      time: string;
      /** @description Number of participants */
      participants: number;
      /** @description Total price for the booking */
      total: number;
      /** @description Average rating for the adventure */
      rating: number;
      /** @description Number of reviews for the adventure */
      reviewsCount: number;
      /**
       * Format: date-time
       * @description ISO 8601 creation timestamp
       */
      createdAt: string;
    };
    CreateBookingRequest: {
      /**
       * Format: date
       * @description Date of the adventure (e.g. 2024-12-31)
       */
      date: string;
      /**
       * Format: time
       * @description Time of the adventure (e.g. 02:00 PM)
       */
      time: string;
      /** @description Number of guests/participants */
      guests: number;
      /** @description Special requests (optional) */
      specialRequests?: string;
    };
  };
}
export type $defs = Record<string, never>;
export interface operations {
  bookAdventure: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBookingRequest"];
      };
    };
    responses: {
      /** @description Booking created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdventureBooking"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAdventureById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example  */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Adventure details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdventureDetails"];
        };
      };
      /** @description Adventure not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getUserAdventureBookings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of user bookings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdventureBookingListItem"][];
        };
      };
    };
  };
  listAdventures: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of adventures */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdventureListItem"][];
        };
      };
    };
  };
}
