/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout user */
    post: operations["logoutUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/signin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in with email and password */
    post: operations["signInUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user account */
    post: operations["signUpUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify OTP code */
    post: operations["verifyOtp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    SignUpRequest: {
      fullName: string;
      passportNumber: string;
      nationality: string;
      /** Format: date */
      dateOfBirth: string;
      /** @enum {string} */
      gender: "M" | "F";
      /** Format: date */
      expiryDate: string;
    } & {
      /** Format: email */
      email: string;
      password: string;
      firstName: string;
      lastName: string;
    };
    SignUpResponse: {
      userId: string;
      /** Format: email */
      email: string;
      firstName?: string;
      lastName?: string;
      requiresOtpVerification: boolean;
      message?: string;
    };
    SignInRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    SignInResponse: {
      accessToken: string;
      refreshToken?: string;
      user: {
        userId: string;
        /** Format: email */
        email: string;
        firstName?: string;
        lastName?: string;
        /** @enum {string} */
        role?: "user" | "admin";
      };
    };
    VerifyOtpRequest: {
      /** Format: email */
      email: string;
      otp: string;
    };
    VerifyOtpResponse: {
      success: boolean;
      message: string;
      accessToken?: string;
      user?: {
        userId: string;
        /** Format: email */
        email: string;
      };
    };
    LogoutResponse: {
      /** @description status */
      status: string;
    };
  };
}
export type $defs = Record<string, never>;
export interface operations {
  logoutUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logout successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
    };
  };
  signInUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description Sign in successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignInResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Account not verified or disabled */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signUpUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      /** @description User created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignUpResponse"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verifyOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyOtpRequest"];
      };
    };
    responses: {
      /** @description OTP verified successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerifyOtpResponse"];
        };
      };
      /** @description Invalid or expired OTP */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
